apiVersion: v1
kind: Namespace
metadata:
  name: springrestbootk8secret-ns
---
apiVersion: v1
kind: Secret
metadata:
  name: springrestbootk8secret-secret
  namespace: springrestbootk8secret-ns
type: Opaque
data:
  db_url: amRiYzpteXNxbDovL2xvY2FsaG9zdDozMzA2L3NwcmluZ0s4U2Ri
  db_username: aGVsbG9LOHNOYW1l
  db_password: SGVsbG9LOHNQYXNzd29yZA==
stringData:
  db_url: 'jdbc:mysql://localhost:3306/springK8Sdb'
  db_username: helloK8sName
  db_password: HelloK8sPassword
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springrestbootk8secret-deployment
  namespace: springrestbootk8secret-ns
spec:
  selector:
    matchLabels:
      app: springrestbootk8secret-app
  replicas: 1 # tells deployment to run 3 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: springrestbootk8secret-app
    spec:
      containers:
      - name: springrestbootk8secret-app
        image: docker.io/krishnamanchikalapudi/springrestbootk8secret:latest
        env:
          - name: db.url
            valueFrom:
              secretKeyRef:
                name: springrestbootk8secret-secret
                key: db_url
          - name: db.username
            valueFrom:
              secretKeyRef:
                name: springrestbootk8secret-secret
                key: db_username
          - name: db.password
            valueFrom:
              secretKeyRef:
                name: springrestbootk8secret-secret
                key: db_password
        ports:
        - containerPort: 8080
          name: server 
        - containerPort: 8081
          name: management
---
apiVersion: v1
kind: Service
metadata:
  name: springrestbootk8secret-service
  namespace: springrestbootk8secret-ns
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 8081
    targetPort: 8081
    name: management
  selector:
    app: springrestbootk8secret-app
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: springrestbootk8secret-ingress
  namespace: springrestbootk8secret-ns
  annotations:
    kubernetes.io/ingress.allow-http: "true"
spec:
  backend:
    serviceName: springrestbootk8secret-service
    servicePort: 8080
---

