server:
   servlet:
    context-path: /
     
spring:
  application:
    name: springrestbootjwt
 
jwt:
  header: Authorization
  secret: example-secret-key

logging:
  level:
    root: INFO
  pattern:
    console: "[%p] %d %c %M - %m%n"
