apiVersion: v1
kind: Service
metadata:
  labels:
    app: springrestbootk8s
  name: springrestbootk8s
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 9376
  selector:
    app: springrestbootk8s
