server:
   servlet:
    context-path: /
   port: 8080
     
spring:
  application:
    name: springbootsocialoauth2
  

            
logging:
  level:
    root: INFO
    com.example.social: DEBUG
  pattern:
    console: "[%p] %d %c %M - %m%n"